fix ScannerTimeoutException; remove HBSExceptionRowLimitReached
java.lang.RuntimeException: org.apache.hadoop.hbase.client.ScannerTimeoutException: 65771ms passed since the last invocation, timeout is currently set to 60000